-- Vimala storefront catalog seed (24 products) — idempotent
-- Run after 01-schema, 02-commerce, 03-storefront-catalog

INSERT INTO products (
  id, name, slug, description, fabric, price, original_price, stock_status,
  is_new, thumbnail, images, sku, weight_grams, inventory_quantity, reserved_quantity,
  department, category_label, sizes, scarcity_note, discount_percent, hover_image_url,
  publish_status, is_active, sort_order
) VALUES (
  'a0000000-0000-4000-8000-000000000001',
  'Kanjivaram Pure Silk Saree',
  'kanjivaram-pure-silk-saree-bridal',
  'Handpicked Kanjivaram pure silk saree for weddings and bridal trousseaus, chosen for its rich drape and temple-worthy zari work.',
  'Kanjivaram',
  22500,
  NULL,
  'low_stock',
  true,
  'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=400',
  ARRAY['https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=400', 'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=400'],
  'VSH-SLK-001',
  500,
  2,
  0,
  'silks',
  'Bridal',
  NULL,
  'Only 2 pieces left',
  NULL,
  'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=400',
  'published',
  true,
  1
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  fabric = EXCLUDED.fabric,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  stock_status = EXCLUDED.stock_status,
  is_new = EXCLUDED.is_new,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  sku = EXCLUDED.sku,
  inventory_quantity = EXCLUDED.inventory_quantity,
  department = EXCLUDED.department,
  category_label = EXCLUDED.category_label,
  sizes = EXCLUDED.sizes,
  scarcity_note = EXCLUDED.scarcity_note,
  discount_percent = EXCLUDED.discount_percent,
  hover_image_url = EXCLUDED.hover_image_url,
  publish_status = EXCLUDED.publish_status,
  is_active = EXCLUDED.is_active,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (
  id, name, slug, description, fabric, price, original_price, stock_status,
  is_new, thumbnail, images, sku, weight_grams, inventory_quantity, reserved_quantity,
  department, category_label, sizes, scarcity_note, discount_percent, hover_image_url,
  publish_status, is_active, sort_order
) VALUES (
  'a0000000-0000-4000-8000-000000000002',
  'Banarasi Zari Bridal Saree',
  'banarasi-zari-bridal-saree',
  'Banarasi zari weave bridal saree with intricate brocade — a festive and wedding favourite from our Kattappana silk collection.',
  'Banarasi',
  18900,
  22000,
  'in_stock',
  false,
  'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=400',
  ARRAY['https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=400'],
  'VSH-SLK-002',
  500,
  25,
  0,
  'silks',
  'Bridal',
  NULL,
  'Selling fast this week',
  14,
  NULL,
  'published',
  true,
  2
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  fabric = EXCLUDED.fabric,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  stock_status = EXCLUDED.stock_status,
  is_new = EXCLUDED.is_new,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  sku = EXCLUDED.sku,
  inventory_quantity = EXCLUDED.inventory_quantity,
  department = EXCLUDED.department,
  category_label = EXCLUDED.category_label,
  sizes = EXCLUDED.sizes,
  scarcity_note = EXCLUDED.scarcity_note,
  discount_percent = EXCLUDED.discount_percent,
  hover_image_url = EXCLUDED.hover_image_url,
  publish_status = EXCLUDED.publish_status,
  is_active = EXCLUDED.is_active,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (
  id, name, slug, description, fabric, price, original_price, stock_status,
  is_new, thumbnail, images, sku, weight_grams, inventory_quantity, reserved_quantity,
  department, category_label, sizes, scarcity_note, discount_percent, hover_image_url,
  publish_status, is_active, sort_order
) VALUES (
  'a0000000-0000-4000-8000-000000000003',
  'Kerala Kasavu Set',
  'kerala-kasavu-set-festive',
  'Classic Kerala Kasavu set in cotton silk — ideal for Onam, Vishu, and festive gatherings across Kerala and beyond.',
  'Cotton Silk',
  4800,
  NULL,
  'low_stock',
  true,
  'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=400',
  ARRAY['https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=400'],
  'VSH-SLK-003',
  500,
  3,
  0,
  'silks',
  'Festive',
  NULL,
  'Only 3 left in standard sizes',
  NULL,
  NULL,
  'published',
  true,
  3
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  fabric = EXCLUDED.fabric,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  stock_status = EXCLUDED.stock_status,
  is_new = EXCLUDED.is_new,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  sku = EXCLUDED.sku,
  inventory_quantity = EXCLUDED.inventory_quantity,
  department = EXCLUDED.department,
  category_label = EXCLUDED.category_label,
  sizes = EXCLUDED.sizes,
  scarcity_note = EXCLUDED.scarcity_note,
  discount_percent = EXCLUDED.discount_percent,
  hover_image_url = EXCLUDED.hover_image_url,
  publish_status = EXCLUDED.publish_status,
  is_active = EXCLUDED.is_active,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (
  id, name, slug, description, fabric, price, original_price, stock_status,
  is_new, thumbnail, images, sku, weight_grams, inventory_quantity, reserved_quantity,
  department, category_label, sizes, scarcity_note, discount_percent, hover_image_url,
  publish_status, is_active, sort_order
) VALUES (
  'a0000000-0000-4000-8000-000000000004',
  'Embroidered Georgette Saree',
  'embroidered-georgette-saree-festive',
  'Lightweight embroidered georgette saree for festive evenings — easy to drape, photograph beautifully, and ship worldwide.',
  'Georgette',
  6800,
  NULL,
  'low_stock',
  false,
  'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=400',
  ARRAY['https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=400'],
  'VSH-WOM-004',
  500,
  3,
  0,
  'women',
  'Festive',
  ARRAY['S', 'M', 'L', 'XL'],
  'Only 3 left in this size',
  NULL,
  NULL,
  'published',
  true,
  4
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  fabric = EXCLUDED.fabric,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  stock_status = EXCLUDED.stock_status,
  is_new = EXCLUDED.is_new,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  sku = EXCLUDED.sku,
  inventory_quantity = EXCLUDED.inventory_quantity,
  department = EXCLUDED.department,
  category_label = EXCLUDED.category_label,
  sizes = EXCLUDED.sizes,
  scarcity_note = EXCLUDED.scarcity_note,
  discount_percent = EXCLUDED.discount_percent,
  hover_image_url = EXCLUDED.hover_image_url,
  publish_status = EXCLUDED.publish_status,
  is_active = EXCLUDED.is_active,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (
  id, name, slug, description, fabric, price, original_price, stock_status,
  is_new, thumbnail, images, sku, weight_grams, inventory_quantity, reserved_quantity,
  department, category_label, sizes, scarcity_note, discount_percent, hover_image_url,
  publish_status, is_active, sort_order
) VALUES (
  'a0000000-0000-4000-8000-000000000005',
  'Designer Anarkali Gown',
  'designer-anarkali-gown-party',
  'Designer Anarkali gown in net and silk — readymade party wear with the finish families expect from Vimala Silk House.',
  'Net & Silk',
  8900,
  NULL,
  'in_stock',
  true,
  'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=400',
  ARRAY['https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=400'],
  'VSH-RDY-005',
  500,
  25,
  0,
  'readymade',
  'Party Wear',
  ARRAY['S', 'M', 'L'],
  NULL,
  NULL,
  NULL,
  'published',
  true,
  5
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  fabric = EXCLUDED.fabric,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  stock_status = EXCLUDED.stock_status,
  is_new = EXCLUDED.is_new,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  sku = EXCLUDED.sku,
  inventory_quantity = EXCLUDED.inventory_quantity,
  department = EXCLUDED.department,
  category_label = EXCLUDED.category_label,
  sizes = EXCLUDED.sizes,
  scarcity_note = EXCLUDED.scarcity_note,
  discount_percent = EXCLUDED.discount_percent,
  hover_image_url = EXCLUDED.hover_image_url,
  publish_status = EXCLUDED.publish_status,
  is_active = EXCLUDED.is_active,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (
  id, name, slug, description, fabric, price, original_price, stock_status,
  is_new, thumbnail, images, sku, weight_grams, inventory_quantity, reserved_quantity,
  department, category_label, sizes, scarcity_note, discount_percent, hover_image_url,
  publish_status, is_active, sort_order
) VALUES (
  'a0000000-0000-4000-8000-000000000006',
  'Printed Cotton Kurti',
  'printed-cotton-kurti-daily-wear',
  'Everyday printed cotton kurti — dependable readymade daily wear from our Kattappana family fashion floor.',
  'Cotton',
  1299,
  1799,
  'in_stock',
  false,
  'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=400',
  ARRAY['https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=400'],
  'VSH-RDY-006',
  500,
  25,
  0,
  'readymade',
  'Daily Wear',
  ARRAY['S', 'M', 'L', 'XL', 'XXL'],
  NULL,
  28,
  NULL,
  'published',
  true,
  6
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  fabric = EXCLUDED.fabric,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  stock_status = EXCLUDED.stock_status,
  is_new = EXCLUDED.is_new,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  sku = EXCLUDED.sku,
  inventory_quantity = EXCLUDED.inventory_quantity,
  department = EXCLUDED.department,
  category_label = EXCLUDED.category_label,
  sizes = EXCLUDED.sizes,
  scarcity_note = EXCLUDED.scarcity_note,
  discount_percent = EXCLUDED.discount_percent,
  hover_image_url = EXCLUDED.hover_image_url,
  publish_status = EXCLUDED.publish_status,
  is_active = EXCLUDED.is_active,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (
  id, name, slug, description, fabric, price, original_price, stock_status,
  is_new, thumbnail, images, sku, weight_grams, inventory_quantity, reserved_quantity,
  department, category_label, sizes, scarcity_note, discount_percent, hover_image_url,
  publish_status, is_active, sort_order
) VALUES (
  'a0000000-0000-4000-8000-000000000007',
  'Men''s Silk Shirt',
  'mens-silk-blend-formal-shirt',
  'Men''s silk blend formal shirt — smart readymade menswear for functions, office, and festive occasions.',
  'Silk Blend',
  2499,
  NULL,
  'in_stock',
  false,
  'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=400',
  ARRAY['https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=400'],
  'VSH-MEN-007',
  500,
  25,
  0,
  'men',
  'Formal',
  ARRAY['38', '40', '42', '44'],
  NULL,
  NULL,
  NULL,
  'published',
  true,
  7
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  fabric = EXCLUDED.fabric,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  stock_status = EXCLUDED.stock_status,
  is_new = EXCLUDED.is_new,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  sku = EXCLUDED.sku,
  inventory_quantity = EXCLUDED.inventory_quantity,
  department = EXCLUDED.department,
  category_label = EXCLUDED.category_label,
  sizes = EXCLUDED.sizes,
  scarcity_note = EXCLUDED.scarcity_note,
  discount_percent = EXCLUDED.discount_percent,
  hover_image_url = EXCLUDED.hover_image_url,
  publish_status = EXCLUDED.publish_status,
  is_active = EXCLUDED.is_active,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (
  id, name, slug, description, fabric, price, original_price, stock_status,
  is_new, thumbnail, images, sku, weight_grams, inventory_quantity, reserved_quantity,
  department, category_label, sizes, scarcity_note, discount_percent, hover_image_url,
  publish_status, is_active, sort_order
) VALUES (
  'a0000000-0000-4000-8000-000000000008',
  'Men''s Dhoti Set',
  'mens-cotton-dhoti-set-traditional',
  'Traditional men''s cotton dhoti set — a staple for temple visits, weddings, and Kerala festive dressing.',
  'Cotton',
  1899,
  NULL,
  'in_stock',
  true,
  'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=400',
  ARRAY['https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=400'],
  'VSH-MEN-008',
  500,
  25,
  0,
  'men',
  'Traditional',
  NULL,
  NULL,
  NULL,
  NULL,
  'published',
  true,
  8
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  fabric = EXCLUDED.fabric,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  stock_status = EXCLUDED.stock_status,
  is_new = EXCLUDED.is_new,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  sku = EXCLUDED.sku,
  inventory_quantity = EXCLUDED.inventory_quantity,
  department = EXCLUDED.department,
  category_label = EXCLUDED.category_label,
  sizes = EXCLUDED.sizes,
  scarcity_note = EXCLUDED.scarcity_note,
  discount_percent = EXCLUDED.discount_percent,
  hover_image_url = EXCLUDED.hover_image_url,
  publish_status = EXCLUDED.publish_status,
  is_active = EXCLUDED.is_active,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (
  id, name, slug, description, fabric, price, original_price, stock_status,
  is_new, thumbnail, images, sku, weight_grams, inventory_quantity, reserved_quantity,
  department, category_label, sizes, scarcity_note, discount_percent, hover_image_url,
  publish_status, is_active, sort_order
) VALUES (
  'a0000000-0000-4000-8000-000000000009',
  'Kids Festive Lehenga',
  'kids-festive-lehenga-silk-blend',
  'Kids festive lehenga in silk blend — readymade children''s occasion wear for weddings and family celebrations.',
  'Silk Blend',
  3200,
  NULL,
  'low_stock',
  false,
  'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=400',
  ARRAY['https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=400'],
  'VSH-KID-009',
  500,
  4,
  0,
  'kids',
  'Festive',
  ARRAY['4-6Y', '6-8Y', '8-10Y'],
  'Only 4 left — festive sizes',
  NULL,
  NULL,
  'published',
  true,
  9
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  fabric = EXCLUDED.fabric,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  stock_status = EXCLUDED.stock_status,
  is_new = EXCLUDED.is_new,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  sku = EXCLUDED.sku,
  inventory_quantity = EXCLUDED.inventory_quantity,
  department = EXCLUDED.department,
  category_label = EXCLUDED.category_label,
  sizes = EXCLUDED.sizes,
  scarcity_note = EXCLUDED.scarcity_note,
  discount_percent = EXCLUDED.discount_percent,
  hover_image_url = EXCLUDED.hover_image_url,
  publish_status = EXCLUDED.publish_status,
  is_active = EXCLUDED.is_active,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (
  id, name, slug, description, fabric, price, original_price, stock_status,
  is_new, thumbnail, images, sku, weight_grams, inventory_quantity, reserved_quantity,
  department, category_label, sizes, scarcity_note, discount_percent, hover_image_url,
  publish_status, is_active, sort_order
) VALUES (
  'a0000000-0000-4000-8000-000000000010',
  'Kids Casual Set',
  'kids-cotton-casual-set',
  'Comfortable kids cotton casual set — everyday readymade children''s wear from our family fashion department.',
  'Cotton',
  899,
  NULL,
  'in_stock',
  false,
  'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=400',
  ARRAY['https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=400'],
  'VSH-KID-010',
  500,
  25,
  0,
  'kids',
  'Daily Wear',
  ARRAY['2-4Y', '4-6Y', '6-8Y'],
  NULL,
  NULL,
  NULL,
  'published',
  true,
  10
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  fabric = EXCLUDED.fabric,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  stock_status = EXCLUDED.stock_status,
  is_new = EXCLUDED.is_new,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  sku = EXCLUDED.sku,
  inventory_quantity = EXCLUDED.inventory_quantity,
  department = EXCLUDED.department,
  category_label = EXCLUDED.category_label,
  sizes = EXCLUDED.sizes,
  scarcity_note = EXCLUDED.scarcity_note,
  discount_percent = EXCLUDED.discount_percent,
  hover_image_url = EXCLUDED.hover_image_url,
  publish_status = EXCLUDED.publish_status,
  is_active = EXCLUDED.is_active,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (
  id, name, slug, description, fabric, price, original_price, stock_status,
  is_new, thumbnail, images, sku, weight_grams, inventory_quantity, reserved_quantity,
  department, category_label, sizes, scarcity_note, discount_percent, hover_image_url,
  publish_status, is_active, sort_order
) VALUES (
  'a0000000-0000-4000-8000-000000000011',
  'Temple Jewelry Set',
  'temple-jewelry-set-gold-plated',
  'Temple jewelry set in gold-plated finish — curated to complete bridal and festive silk saree looks.',
  'Gold-plated',
  4500,
  NULL,
  'in_stock',
  true,
  'https://images.unsplash.com/photo-1611652022419-a9419f74343d?w=400',
  ARRAY['https://images.unsplash.com/photo-1611652022419-a9419f74343d?w=400'],
  'VSH-ACC-011',
  500,
  25,
  0,
  'accessories',
  'Jewelry',
  NULL,
  NULL,
  NULL,
  NULL,
  'published',
  true,
  11
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  fabric = EXCLUDED.fabric,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  stock_status = EXCLUDED.stock_status,
  is_new = EXCLUDED.is_new,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  sku = EXCLUDED.sku,
  inventory_quantity = EXCLUDED.inventory_quantity,
  department = EXCLUDED.department,
  category_label = EXCLUDED.category_label,
  sizes = EXCLUDED.sizes,
  scarcity_note = EXCLUDED.scarcity_note,
  discount_percent = EXCLUDED.discount_percent,
  hover_image_url = EXCLUDED.hover_image_url,
  publish_status = EXCLUDED.publish_status,
  is_active = EXCLUDED.is_active,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (
  id, name, slug, description, fabric, price, original_price, stock_status,
  is_new, thumbnail, images, sku, weight_grams, inventory_quantity, reserved_quantity,
  department, category_label, sizes, scarcity_note, discount_percent, hover_image_url,
  publish_status, is_active, sort_order
) VALUES (
  'a0000000-0000-4000-8000-000000000012',
  'Kundan Earrings',
  'kundan-earrings-bridal',
  'Kundan earrings chosen to complement our silk and readymade lines — finishing touches for wedding and festive outfits.',
  'Kundan',
  1800,
  NULL,
  'in_stock',
  false,
  'https://images.unsplash.com/photo-1611652022419-a9419f74343d?w=400',
  ARRAY['https://images.unsplash.com/photo-1611652022419-a9419f74343d?w=400'],
  'VSH-ACC-012',
  500,
  25,
  0,
  'accessories',
  'Jewelry',
  NULL,
  NULL,
  NULL,
  NULL,
  'published',
  true,
  12
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  fabric = EXCLUDED.fabric,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  stock_status = EXCLUDED.stock_status,
  is_new = EXCLUDED.is_new,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  sku = EXCLUDED.sku,
  inventory_quantity = EXCLUDED.inventory_quantity,
  department = EXCLUDED.department,
  category_label = EXCLUDED.category_label,
  sizes = EXCLUDED.sizes,
  scarcity_note = EXCLUDED.scarcity_note,
  discount_percent = EXCLUDED.discount_percent,
  hover_image_url = EXCLUDED.hover_image_url,
  publish_status = EXCLUDED.publish_status,
  is_active = EXCLUDED.is_active,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (
  id, name, slug, description, fabric, price, original_price, stock_status,
  is_new, thumbnail, images, sku, weight_grams, inventory_quantity, reserved_quantity,
  department, category_label, sizes, scarcity_note, discount_percent, hover_image_url,
  publish_status, is_active, sort_order
) VALUES (
  'a0000000-0000-4000-8000-000000000013',
  'Linen Summer Saree',
  'linen-summer-saree-kerala',
  'Breathable linen summer saree — light Kerala-friendly fabric for warm-weather festive and casual ethnic wear.',
  'Linen',
  3500,
  NULL,
  'in_stock',
  true,
  'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=400',
  ARRAY['https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=400'],
  'VSH-SUM-013',
  500,
  25,
  0,
  'summer',
  'Summer',
  NULL,
  NULL,
  NULL,
  NULL,
  'published',
  true,
  13
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  fabric = EXCLUDED.fabric,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  stock_status = EXCLUDED.stock_status,
  is_new = EXCLUDED.is_new,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  sku = EXCLUDED.sku,
  inventory_quantity = EXCLUDED.inventory_quantity,
  department = EXCLUDED.department,
  category_label = EXCLUDED.category_label,
  sizes = EXCLUDED.sizes,
  scarcity_note = EXCLUDED.scarcity_note,
  discount_percent = EXCLUDED.discount_percent,
  hover_image_url = EXCLUDED.hover_image_url,
  publish_status = EXCLUDED.publish_status,
  is_active = EXCLUDED.is_active,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (
  id, name, slug, description, fabric, price, original_price, stock_status,
  is_new, thumbnail, images, sku, weight_grams, inventory_quantity, reserved_quantity,
  department, category_label, sizes, scarcity_note, discount_percent, hover_image_url,
  publish_status, is_active, sort_order
) VALUES (
  'a0000000-0000-4000-8000-000000000014',
  'Cotton Churidar Set',
  'cotton-churidar-set-summer',
  'Cotton churidar set for summer — readymade comfort wear in standard sizes, ideal for daily ethnic dressing.',
  'Cotton',
  2100,
  NULL,
  'in_stock',
  false,
  'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=400',
  ARRAY['https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=400'],
  'VSH-SUM-014',
  500,
  25,
  0,
  'summer',
  'Summer',
  ARRAY['S', 'M', 'L'],
  NULL,
  NULL,
  NULL,
  'published',
  true,
  14
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  fabric = EXCLUDED.fabric,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  stock_status = EXCLUDED.stock_status,
  is_new = EXCLUDED.is_new,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  sku = EXCLUDED.sku,
  inventory_quantity = EXCLUDED.inventory_quantity,
  department = EXCLUDED.department,
  category_label = EXCLUDED.category_label,
  sizes = EXCLUDED.sizes,
  scarcity_note = EXCLUDED.scarcity_note,
  discount_percent = EXCLUDED.discount_percent,
  hover_image_url = EXCLUDED.hover_image_url,
  publish_status = EXCLUDED.publish_status,
  is_active = EXCLUDED.is_active,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (
  id, name, slug, description, fabric, price, original_price, stock_status,
  is_new, thumbnail, images, sku, weight_grams, inventory_quantity, reserved_quantity,
  department, category_label, sizes, scarcity_note, discount_percent, hover_image_url,
  publish_status, is_active, sort_order
) VALUES (
  'a0000000-0000-4000-8000-000000000015',
  'Stocklot Men''s Shirt',
  'stocklot-mens-cotton-shirt-clearance',
  'Value stocklot men''s cotton shirt — clearance readymade menswear at an accessible price point.',
  'Cotton',
  599,
  1299,
  'in_stock',
  false,
  'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=400',
  ARRAY['https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=400'],
  'VSH-STK-015',
  500,
  25,
  0,
  'stocklot',
  'Clearance',
  NULL,
  NULL,
  54,
  NULL,
  'published',
  true,
  15
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  fabric = EXCLUDED.fabric,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  stock_status = EXCLUDED.stock_status,
  is_new = EXCLUDED.is_new,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  sku = EXCLUDED.sku,
  inventory_quantity = EXCLUDED.inventory_quantity,
  department = EXCLUDED.department,
  category_label = EXCLUDED.category_label,
  sizes = EXCLUDED.sizes,
  scarcity_note = EXCLUDED.scarcity_note,
  discount_percent = EXCLUDED.discount_percent,
  hover_image_url = EXCLUDED.hover_image_url,
  publish_status = EXCLUDED.publish_status,
  is_active = EXCLUDED.is_active,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (
  id, name, slug, description, fabric, price, original_price, stock_status,
  is_new, thumbnail, images, sku, weight_grams, inventory_quantity, reserved_quantity,
  department, category_label, sizes, scarcity_note, discount_percent, hover_image_url,
  publish_status, is_active, sort_order
) VALUES (
  'a0000000-0000-4000-8000-000000000016',
  'Stocklot Kurti Pack',
  'stocklot-kurti-pack-clearance',
  'Stocklot kurti pack — bundled readymade value picks from our clearance floor in Kattappana.',
  'Mixed',
  999,
  2499,
  'in_stock',
  false,
  'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=400',
  ARRAY['https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=400'],
  'VSH-STK-016',
  500,
  25,
  0,
  'stocklot',
  'Clearance',
  NULL,
  NULL,
  60,
  NULL,
  'published',
  true,
  16
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  fabric = EXCLUDED.fabric,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  stock_status = EXCLUDED.stock_status,
  is_new = EXCLUDED.is_new,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  sku = EXCLUDED.sku,
  inventory_quantity = EXCLUDED.inventory_quantity,
  department = EXCLUDED.department,
  category_label = EXCLUDED.category_label,
  sizes = EXCLUDED.sizes,
  scarcity_note = EXCLUDED.scarcity_note,
  discount_percent = EXCLUDED.discount_percent,
  hover_image_url = EXCLUDED.hover_image_url,
  publish_status = EXCLUDED.publish_status,
  is_active = EXCLUDED.is_active,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (
  id, name, slug, description, fabric, price, original_price, stock_status,
  is_new, thumbnail, images, sku, weight_grams, inventory_quantity, reserved_quantity,
  department, category_label, sizes, scarcity_note, discount_percent, hover_image_url,
  publish_status, is_active, sort_order
) VALUES (
  'a0000000-0000-4000-8000-000000000017',
  'Chanderi Silk Saree',
  'chanderi-silk-saree-festive',
  'Chanderi silk saree with a refined festive drape — handpicked for Onam, weddings, and special occasions.',
  'Chanderi',
  7500,
  NULL,
  'in_stock',
  false,
  'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=400',
  ARRAY['https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=400'],
  'VSH-SLK-017',
  500,
  25,
  0,
  'silks',
  'Festive',
  NULL,
  'Selling fast this week',
  NULL,
  NULL,
  'published',
  true,
  17
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  fabric = EXCLUDED.fabric,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  stock_status = EXCLUDED.stock_status,
  is_new = EXCLUDED.is_new,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  sku = EXCLUDED.sku,
  inventory_quantity = EXCLUDED.inventory_quantity,
  department = EXCLUDED.department,
  category_label = EXCLUDED.category_label,
  sizes = EXCLUDED.sizes,
  scarcity_note = EXCLUDED.scarcity_note,
  discount_percent = EXCLUDED.discount_percent,
  hover_image_url = EXCLUDED.hover_image_url,
  publish_status = EXCLUDED.publish_status,
  is_active = EXCLUDED.is_active,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (
  id, name, slug, description, fabric, price, original_price, stock_status,
  is_new, thumbnail, images, sku, weight_grams, inventory_quantity, reserved_quantity,
  department, category_label, sizes, scarcity_note, discount_percent, hover_image_url,
  publish_status, is_active, sort_order
) VALUES (
  'a0000000-0000-4000-8000-000000000018',
  'Office Wear Salwar Set',
  'office-wear-salwar-set-crepe',
  'Office wear salwar set in crepe — polished readymade ethnic workwear in standard sizes.',
  'Crepe',
  3200,
  NULL,
  'in_stock',
  false,
  'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=400',
  ARRAY['https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=400'],
  'VSH-WOM-018',
  500,
  25,
  0,
  'women',
  'Office Wear',
  ARRAY['S', 'M', 'L', 'XL'],
  NULL,
  NULL,
  NULL,
  'published',
  true,
  18
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  fabric = EXCLUDED.fabric,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  stock_status = EXCLUDED.stock_status,
  is_new = EXCLUDED.is_new,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  sku = EXCLUDED.sku,
  inventory_quantity = EXCLUDED.inventory_quantity,
  department = EXCLUDED.department,
  category_label = EXCLUDED.category_label,
  sizes = EXCLUDED.sizes,
  scarcity_note = EXCLUDED.scarcity_note,
  discount_percent = EXCLUDED.discount_percent,
  hover_image_url = EXCLUDED.hover_image_url,
  publish_status = EXCLUDED.publish_status,
  is_active = EXCLUDED.is_active,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (
  id, name, slug, description, fabric, price, original_price, stock_status,
  is_new, thumbnail, images, sku, weight_grams, inventory_quantity, reserved_quantity,
  department, category_label, sizes, scarcity_note, discount_percent, hover_image_url,
  publish_status, is_active, sort_order
) VALUES (
  'a0000000-0000-4000-8000-000000000019',
  'Men''s Formal Trouser',
  'mens-formal-trouser-poly-wool',
  'Men''s formal trouser in poly wool blend — readymade menswear for office and function dressing.',
  'Poly Wool',
  1699,
  NULL,
  'in_stock',
  false,
  'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=400',
  ARRAY['https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=400'],
  'VSH-MEN-019',
  500,
  25,
  0,
  'men',
  'Formal',
  ARRAY['30', '32', '34', '36'],
  NULL,
  NULL,
  NULL,
  'published',
  true,
  19
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  fabric = EXCLUDED.fabric,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  stock_status = EXCLUDED.stock_status,
  is_new = EXCLUDED.is_new,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  sku = EXCLUDED.sku,
  inventory_quantity = EXCLUDED.inventory_quantity,
  department = EXCLUDED.department,
  category_label = EXCLUDED.category_label,
  sizes = EXCLUDED.sizes,
  scarcity_note = EXCLUDED.scarcity_note,
  discount_percent = EXCLUDED.discount_percent,
  hover_image_url = EXCLUDED.hover_image_url,
  publish_status = EXCLUDED.publish_status,
  is_active = EXCLUDED.is_active,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (
  id, name, slug, description, fabric, price, original_price, stock_status,
  is_new, thumbnail, images, sku, weight_grams, inventory_quantity, reserved_quantity,
  department, category_label, sizes, scarcity_note, discount_percent, hover_image_url,
  publish_status, is_active, sort_order
) VALUES (
  'a0000000-0000-4000-8000-000000000020',
  'Bridal Silk Lehenga',
  'bridal-silk-lehenga-pure-silk',
  'Pure silk bridal lehenga — a statement wedding piece from our bridal silk collection, shipped with protective packaging.',
  'Pure Silk',
  35000,
  NULL,
  'low_stock',
  true,
  'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=400',
  ARRAY['https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=400'],
  'VSH-SLK-020',
  500,
  2,
  0,
  'silks',
  'Bridal',
  NULL,
  'Only 2 pieces left',
  NULL,
  NULL,
  'published',
  true,
  20
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  fabric = EXCLUDED.fabric,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  stock_status = EXCLUDED.stock_status,
  is_new = EXCLUDED.is_new,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  sku = EXCLUDED.sku,
  inventory_quantity = EXCLUDED.inventory_quantity,
  department = EXCLUDED.department,
  category_label = EXCLUDED.category_label,
  sizes = EXCLUDED.sizes,
  scarcity_note = EXCLUDED.scarcity_note,
  discount_percent = EXCLUDED.discount_percent,
  hover_image_url = EXCLUDED.hover_image_url,
  publish_status = EXCLUDED.publish_status,
  is_active = EXCLUDED.is_active,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (
  id, name, slug, description, fabric, price, original_price, stock_status,
  is_new, thumbnail, images, sku, weight_grams, inventory_quantity, reserved_quantity,
  department, category_label, sizes, scarcity_note, discount_percent, hover_image_url,
  publish_status, is_active, sort_order
) VALUES (
  'a0000000-0000-4000-8000-000000000021',
  'Handbag — Ethnic',
  'ethnic-embroidered-handbag',
  'Ethnic embroidered handbag — lifestyle accessory curated to match sarees and festive readymade outfits.',
  'Embroidered',
  2200,
  NULL,
  'in_stock',
  false,
  'https://images.unsplash.com/photo-1611652022419-a9419f74343d?w=400',
  ARRAY['https://images.unsplash.com/photo-1611652022419-a9419f74343d?w=400'],
  'VSH-ACC-021',
  500,
  25,
  0,
  'accessories',
  'Bags',
  NULL,
  NULL,
  NULL,
  NULL,
  'published',
  true,
  21
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  fabric = EXCLUDED.fabric,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  stock_status = EXCLUDED.stock_status,
  is_new = EXCLUDED.is_new,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  sku = EXCLUDED.sku,
  inventory_quantity = EXCLUDED.inventory_quantity,
  department = EXCLUDED.department,
  category_label = EXCLUDED.category_label,
  sizes = EXCLUDED.sizes,
  scarcity_note = EXCLUDED.scarcity_note,
  discount_percent = EXCLUDED.discount_percent,
  hover_image_url = EXCLUDED.hover_image_url,
  publish_status = EXCLUDED.publish_status,
  is_active = EXCLUDED.is_active,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (
  id, name, slug, description, fabric, price, original_price, stock_status,
  is_new, thumbnail, images, sku, weight_grams, inventory_quantity, reserved_quantity,
  department, category_label, sizes, scarcity_note, discount_percent, hover_image_url,
  publish_status, is_active, sort_order
) VALUES (
  'a0000000-0000-4000-8000-000000000022',
  'Palazzo Set',
  'rayon-palazzo-set-casual',
  'Rayon palazzo readymade set — relaxed casual ethnic wear for everyday family fashion shopping.',
  'Rayon',
  1899,
  NULL,
  'in_stock',
  false,
  'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=400',
  ARRAY['https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=400'],
  'VSH-RDY-022',
  500,
  25,
  0,
  'readymade',
  'Casual',
  ARRAY['S', 'M', 'L'],
  NULL,
  NULL,
  NULL,
  'published',
  true,
  22
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  fabric = EXCLUDED.fabric,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  stock_status = EXCLUDED.stock_status,
  is_new = EXCLUDED.is_new,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  sku = EXCLUDED.sku,
  inventory_quantity = EXCLUDED.inventory_quantity,
  department = EXCLUDED.department,
  category_label = EXCLUDED.category_label,
  sizes = EXCLUDED.sizes,
  scarcity_note = EXCLUDED.scarcity_note,
  discount_percent = EXCLUDED.discount_percent,
  hover_image_url = EXCLUDED.hover_image_url,
  publish_status = EXCLUDED.publish_status,
  is_active = EXCLUDED.is_active,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (
  id, name, slug, description, fabric, price, original_price, stock_status,
  is_new, thumbnail, images, sku, weight_grams, inventory_quantity, reserved_quantity,
  department, category_label, sizes, scarcity_note, discount_percent, hover_image_url,
  publish_status, is_active, sort_order
) VALUES (
  'a0000000-0000-4000-8000-000000000023',
  'Mysore Silk Saree',
  'mysore-silk-saree-premium',
  'Premium Mysore silk saree — soft lustre and classic drape from our curated Kerala silk sarees online collection.',
  'Mysore Silk',
  14200,
  NULL,
  'in_stock',
  false,
  'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=400',
  ARRAY['https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=400'],
  'VSH-SLK-023',
  500,
  25,
  0,
  'silks',
  'Premium',
  NULL,
  NULL,
  NULL,
  NULL,
  'published',
  true,
  23
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  fabric = EXCLUDED.fabric,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  stock_status = EXCLUDED.stock_status,
  is_new = EXCLUDED.is_new,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  sku = EXCLUDED.sku,
  inventory_quantity = EXCLUDED.inventory_quantity,
  department = EXCLUDED.department,
  category_label = EXCLUDED.category_label,
  sizes = EXCLUDED.sizes,
  scarcity_note = EXCLUDED.scarcity_note,
  discount_percent = EXCLUDED.discount_percent,
  hover_image_url = EXCLUDED.hover_image_url,
  publish_status = EXCLUDED.publish_status,
  is_active = EXCLUDED.is_active,
  sort_order = EXCLUDED.sort_order;

INSERT INTO products (
  id, name, slug, description, fabric, price, original_price, stock_status,
  is_new, thumbnail, images, sku, weight_grams, inventory_quantity, reserved_quantity,
  department, category_label, sizes, scarcity_note, discount_percent, hover_image_url,
  publish_status, is_active, sort_order
) VALUES (
  'a0000000-0000-4000-8000-000000000024',
  'Kids School Uniform Set',
  'kids-school-uniform-cotton-set',
  'Kids cotton school uniform set — durable readymade children''s daily wear in standard age sizes.',
  'Cotton',
  750,
  NULL,
  'in_stock',
  false,
  'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=400',
  ARRAY['https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=400'],
  'VSH-KID-024',
  500,
  25,
  0,
  'kids',
  'Daily Wear',
  ARRAY['4-6Y', '6-8Y', '8-10Y', '10-12Y'],
  NULL,
  NULL,
  NULL,
  'published',
  true,
  24
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  fabric = EXCLUDED.fabric,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  stock_status = EXCLUDED.stock_status,
  is_new = EXCLUDED.is_new,
  thumbnail = EXCLUDED.thumbnail,
  images = EXCLUDED.images,
  sku = EXCLUDED.sku,
  inventory_quantity = EXCLUDED.inventory_quantity,
  department = EXCLUDED.department,
  category_label = EXCLUDED.category_label,
  sizes = EXCLUDED.sizes,
  scarcity_note = EXCLUDED.scarcity_note,
  discount_percent = EXCLUDED.discount_percent,
  hover_image_url = EXCLUDED.hover_image_url,
  publish_status = EXCLUDED.publish_status,
  is_active = EXCLUDED.is_active,
  sort_order = EXCLUDED.sort_order;

